project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - index.qmd
      - about.qmd 
    logo: "C:/Users/gaman/OneDrive - baudoin/Bureau/Cours M2DA/Projet R/iaschool.png"
    tools:
      
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
      
    
  favicon: "bust-mask-2.png" 
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

